# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f87d1a49274f1240b9720aa731bbd830cc29281522c834306583b58e669e34ebcac6414f2fadf0e32192ff3f0a992bc59bd378dbf7e4353436e90db05614710

test:
  secret_key_base: 5cc4a5731177d1c04c8f5bcea988d07c37d9f68e3fa463a2690f42362a7d7ab3fca735b5ffdc8f0c94064e4ea993cc340477c0290d79bb9b02f336080cb061da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
